name = "myjobtrack-api"
main = "src/api/index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "development"

# D1 Database bindings
[[d1_databases]]
binding = "DB"
database_name = "myjobtrack-db"
database_id = "d729dbcd-e5de-4073-9bcb-7d9f1544729d"

# CORS settings for frontend
[env.development]
vars = { CORS_ORIGIN = "http://localhost:5173" }

[env.production]
vars = { CORS_ORIGIN = "https://myjobtrack.app" }

# Routes for API endpoints
[[routes]]
pattern = "api.myjobtrack.app/*"
zone_name = "myjobtrack.app"
