name = "myjobtrack-api"
main = "src/api/index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# Default environment variables (used when no specific environment is set)
[vars]
ENVIRONMENT = "production"
CORS_ORIGIN = "https://myjobtrack.app"
# SLACK_WEBHOOK_URL is set as a secret via: wrangler secret put SLACK_WEBHOOK_URL

# D1 Database bindings
[[d1_databases]]
binding = "DB"
database_name = "myjobtrack-db"
database_id = "d729dbcd-e5de-4073-9bcb-7d9f1544729d"
migrations_dir = "database/migrations"

# Development environment (use with: wrangler dev or wrangler deploy --env development)
[env.development]
vars = { ENVIRONMENT = "development", CORS_ORIGIN = "http://localhost:5173" }
# SLACK_WEBHOOK_URL is set as a secret via: wrangler secret put SLACK_WEBHOOK_URL --env development

[[env.development.d1_databases]]
binding = "DB"
database_name = "myjobtrack-db"
database_id = "d729dbcd-e5de-4073-9bcb-7d9f1544729d"
migrations_dir = "database/migrations"

# Production environment (use with: wrangler deploy --env production)
[env.production]
vars = { ENVIRONMENT = "production", CORS_ORIGIN = "https://myjobtrack.app" }
# SLACK_WEBHOOK_URL is set as a secret via: wrangler secret put SLACK_WEBHOOK_URL --env production

[[env.production.d1_databases]]
binding = "DB"
database_name = "myjobtrack-db"
database_id = "d729dbcd-e5de-4073-9bcb-7d9f1544729d"
migrations_dir = "database/migrations"
