export { default as HeroSection } from './HeroSection';
export { default as FeaturesSection } from './FeaturesSection';
export { default as QRCodeShowcase } from './QRCodeShowcase';
export { default as BenefitsSection } from './BenefitsSection';
export { default as TestimonialsSection } from './TestimonialsSection';
export { default as CTASection } from './CTASection';
export { default as NavBar } from './NavBar';
export { default as Footer } from './Footer';
export { default as SchemaSEO } from './SchemaSEO';
